"""Remove actual_hours column from tasks table

Revision ID: 699d11d39f42
Revises: e2f3g4h5i6j7
Create Date: 2026-01-07 19:04:49.676768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '699d11d39f42'
down_revision = 'e2f3g4h5i6j7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_deps_depends_on', table_name='task_dependencies')
    op.drop_constraint('task_dependencies_task_id_fkey', 'task_dependencies', type_='foreignkey')
    op.drop_constraint('task_dependencies_depends_on_task_id_fkey', 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'task_dependencies', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'task_dependencies', 'tasks', ['depends_on_task_id'], ['id'])
    op.drop_constraint('tasks_parent_task_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.drop_column('tasks', 'actual_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('actual_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_parent_task_id_fkey', 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.create_foreign_key('task_dependencies_depends_on_task_id_fkey', 'task_dependencies', 'tasks', ['depends_on_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('task_dependencies_task_id_fkey', 'task_dependencies', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_task_deps_depends_on', 'task_dependencies', ['depends_on_task_id'], unique=False)
    # ### end Alembic commands ###
